mycar/myapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('news/', include('news.urls', namespace='news'))
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

mycar/news/urls.py
from django.urls import path

from news.views import news_list

app_name = 'news'

urlpatterns = [
    path('news/', news_list, name='news_list'),
]

mycar/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('posts/<int:post_id>/edit/', views.post_edit,
         name='edit'),
    path('', views.index,
         name='index'),
    path('create/', views.post_create,
         name='create'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('group/<slug:slug>/', views.group_posts,
         name='group_list'),
    path('profile/<str:username>/', views.profile,
         name='profile'),
    path('posts/<int:post_id>/', views.post_detail,
         name='post_detail'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
    path('delete/<post_id>', views.delete_post, name='delete')
]

mycar/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """Модель групп"""
    title = models.CharField(
        max_length=200,
        verbose_name='Заголовок')
    slug = models.SlugField(
        unique=True,
        verbose_name='ЧПУ')
    description = models.TextField(
        max_length=200,
        verbose_name='Описание'
    )

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    """Модель постов"""
    text = models.TextField(
        max_length=3000,
        help_text='Введите текст поста',
        verbose_name='Текст поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Тут можно загрузить картинку'
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = 'Посты'
        verbose_name = 'Пост'

    def __str__(self):
        return self.text


class Comment(models.Model):
    '''Модель Коментарий'''
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор')
    text = models.TextField(
        verbose_name='Коментарий',
        help_text='Можно написать комментарий'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Создан')
    updated = models.DateTimeField(
        auto_now=True,
        verbose_name='Обнавлен')
    active = models.BooleanField(
        default=True,
        verbose_name='Активен')

    class Meta:
        ordering = ['-created']
        verbose_name_plural = 'Коментарии'
        verbose_name = 'Коментарий'

    def __str__(self):
        return self.text[:10]


class Follow(models.Model):
    '''Модель подписок'''
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор')

    class Meta:
        constraints = [models.UniqueConstraint(fields=['user', 'author'],
                                               name='unique_following')]
        verbose_name_plural = 'Подписки'
        verbose_name = 'Подписка'

    def __str__(self):
        return f'{self.user} подписался на {self.author}'

mycar/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

mycar/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.vary import vary_on_cookie
from django.views.decorators.cache import cache_page


from posts.forms import CommentForm, PostForm
from .models import Follow, Post, Group, User
from .utils import get_page


@cache_page(20, key_prefix='index_page')
@vary_on_cookie
def index(request):
    """Выводит шаблон главной страницы"""
    post_list = Post.objects.select_related('group', 'author')
    page_obj = get_page(request, post_list)
    return render(request, 'posts/index.html', {"page_obj": page_obj})


def group_posts(request, slug):
    """Выводит шаблон с группами постов"""
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('author')
    page_obj = get_page(request, post_list)
    return render(request, 'posts/group_list.html', {'group': group,
                                                     'page_obj': page_obj
                                                     })


def profile(request, username):
    """Выводит шаблон профайла пользователя"""
    author = get_object_or_404(User, username=username)
    post = author.posts.all()
    page_obj = get_page(request, post)
    following = (request.user.is_authenticated and author.following.filter(
        user=request.user).exists()
    )
    return render(request, 'posts/profile.html', {
        'page_obj': page_obj,
        'author': author,
        'following': following})


def post_detail(request, post_id):
    """Подробности публикации"""
    post = get_object_or_404(Post, pk=post_id)
    return render(request,
                  'posts/post_detail.html',
                  {'post': post,
                   'form': CommentForm(),
                   'comments': post.comments.all()})


@login_required
def post_create(request):
    """Создания поста"""
    form = PostForm(request.POST or None,
                    files=request.FILES or None,)
    if form.is_valid():
        create_post = form.save(commit=False)
        create_post.author = request.user
        create_post.save()
        return redirect('posts:profile', create_post.author)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    """Редактирование поста"""
    edit_post = get_object_or_404(Post, id=post_id)
    if request.user != edit_post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=edit_post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    return render(request, 'posts/create_post.html', {'form': form,
                                                      'is_edit': True})


@login_required
def add_comment(request, post_id):
    """Модель добавления комментария"""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """информация о текущем пользователе доступна в переменной"""
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = get_page(request, posts)
    return render(request, 'posts/follow.html', {
        'page_obj': page_obj}
    )


@login_required
def profile_follow(request, username):
    """Подписаться на автора"""
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', author)


@login_required
def profile_unfollow(request, username):
    """Дизлайк, отписка"""
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(
        user=request.user,
        author=author
    )
    if follow.exists():
        follow.delete()
    return redirect('posts:profile', username)


@login_required
def delete_post(request, post_id=None):
    '''Удаление поста'''
    post_list = Post.objects.select_related('group', 'author')
    page_obj = get_page(request, post_list)
    post_to_delete = Post.objects.get(id=post_id)
    post_to_delete.delete()
    return render(request, 'posts/index.html', {"page_obj": page_obj})

mycar/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}{% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">{% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}</div>
      <div class="card-body">
         {% include 'includes/error_forms.html' %}
         <form method="post" enctype="multipart/form-data" action="{{ request.get_full_path }}">
          {% csrf_token %}
          {% include 'includes/forms_field.html' %}
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">{% if is_edit %}Сохранить{% else %}Добавить{% endif %}</button>
          </div>
        </form>
      </div>
   </div>
  </div>
</div>
{% endblock %}

mycar/templates/posts/follow.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %} Подписки {% endblock title %}
{% block content %}
  {% include 'posts/includes/switcher.html' with follow=True %}
    {% for post in page_obj %}
      {% include 'includes/card_post.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
      {% include 'posts/includes/paginator.html' %}
{% endblock content %}

mycar/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  {{ group }}
{% endblock title %}
{% block content %}
  <h1> {{ group.title }} </h1>
  <p>{{ group.description|linebreaksbr }}</p>
  {% for post in page_obj %}
    <hr>
    {% include 'includes/card_post.html' %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

mycar/templates/posts/index.html
{% extends "base.html" %}
  {% block content %}
    {% include 'posts/includes/switcher.html' with index=True %}
    <h2>Последние обновления на сайте</h2>
    {% for post in page_obj %}
      {% include 'includes/card_post.html' %}
      {% if not forloop.last %} 
        <hr>
      {% endif %}
    {% endfor %}
      {% include 'posts/includes/paginator.html' %}
{% endblock content %}

mycar/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Пост {{ post|truncatechars:30 }}{% endblock title %}
{% block content %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:'d E Y' }}
      </li>
      <li class="list-group-item">
        Группа:
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}"> {{ post.group.slug }}</a>
          {% else %}
          ---Пусто---
        {% endif %}
      </li>
      <li class="list-group-item">
        Автор: {{ post.author.username }}
      </li>
      <li class="list-group-item">
        Всего постов автора: {{ post.author.posts.count }}
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя {{ post.author.username }}</a>
      </li>
    </ul> 
  </aside>
  <article class="col-12 col-md-9">
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img-top" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text|linebreaksbr }}</p>
    {% if user == post.author %}
      <a class="btn btn-primary" href="{% url 'posts:edit' post.id %}">редактировать запись</a>
      <a class="btn btn-danger" href="{% url 'posts:delete' post.id %}">Удалить</a>
    {% endif %}
    {% include 'includes/comment.html' %}
  </article>
</div>
{% endblock %}

mycar/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}{{ author.username }}
профайл пользователя
{% endblock %}
{% block content %}
    <h1>Все посты пользователя {{ author.username }}</h1>
    <h3>Всего постов: {{ author.posts.count }}</h3>
    <h3>Всего подписот: {{ author.following.count }}</h3>
    {% if request.user != author %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
          Отписаться
        </a>
          {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button" 
        >
          Подписаться
        </a>
     {% endif %}
    {% endif %}
    {% for post in page_obj %}
      {% include 'includes/card_post.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %}