mycar/myapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('news/', include('news.urls', namespace='news'))
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

mycar/news/urls.py
from django.urls import path

from news.views import news_list

app_name = 'news'

urlpatterns = [
    path('news/', news_list, name='news_list'),
]

mycar/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('posts/<int:post_id>/edit/', views.post_edit,
         name='edit'),
    path('', views.index,
         name='index'),
    path('create/', views.post_create,
         name='create'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('group/<slug:slug>/', views.group_posts,
         name='group_list'),
    path('profile/<str:username>/', views.profile,
         name='profile'),
    path('posts/<int:post_id>/', views.post_detail,
         name='post_detail'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
    path('delete/<post_id>', views.delete_post, name='delete')
]

mycar/templates/includes/card_post.html
{% load thumbnail %}
<article>  
  <ul>  
    <li>
      Автор: {{ post.author.get_full_name }}
      <a href="{% url 'posts:profile' post.author %}">Профайл пользователя</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:'d E Y' }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
   <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text|linebreaksbr }}</p> 
   <p>
    <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>
    <br>
  </p>
  {% if post.group and not group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group }}</a>
  {% endif %}
</article>

mycar/templates/includes/comment.html
{% load user_filters %}
{% if comments.count != 0 %}
{% with comments.count as total_comments %}
  <hr>
  <figure>
    <blockquote class="blockquote">
      <div class="shadow-sm p-2 bg-white rounded">
        Комментариев {{ total_comments }}
      </div>
    </blockquote>
  </figure>
{% endwith %}
{% endif %}
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
      <div class="card-body">
        <form method="post" action="{% url 'posts:add_comment' post.id %}">
          {% csrf_token %}      
          <div class="form-group mb-2">
            {{ form.text|addclass:"form-control" }}
          </div>
          <button type="submit" class="btn btn-primary">Отправить комментарий</button>
        </form>
      </div>
  </div>
{% endif %}
{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <div class="alert alert-primary" role="alert">
        {{ comment.created|date:'d E Y' }} <a href="{% url 'posts:profile' comment.author.username %}">{{ comment.author.get_full_name }}</a>:
      </div>
      <figure>
        <blockquote class="blockquote">
          <div class="shadow-sm p-3 bg-white">
            {{ comment.text|linebreaks }}
          </div>
        </blockquote>
      </figure>
    </div>
  </div>
{% empty %}
<hr>
<figure>
  <blockquote class="blockquote">
    <div class="shadow-sm p-2 bg-white rounded">
      Тут пока нет комментарий 
    </div>
  </blockquote>
</figure>
{% endfor %}

mycar/templates/includes/error_forms.html
{% load user_filters %}
{% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}            
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
{% endif %}

mycar/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:blue">Я</span><span style="color:red">мы</span>Авто</p>    
</footer> 

mycar/templates/includes/forms_field.html
{% for field in form %}
  <div class="form-group row my-3 p-3">
   <label for="{{ field.id_for_label }}">
     {{ field.label }}
      {% if field.field.required %}
       <span class="required text-danger">*</span>
      {% endif %}
   </label>
   {{ field }}
   {% if field.help_text %}
     <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
   {% endif %}
  </div>
{% endfor %}

mycar/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:blue">Я</span><span style="color:red">мы</span>Авто</p> 
      </a>
      <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name == 'news:news_list' %}active{% endif %}" href="{% url 'news:news_list' %}">Новости</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link {% if view_name == 'about:author' %}active{% endif %}" href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}" href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name == 'posts:create' %}active{% endif %}" href="{% url 'posts:create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name == 'users:password_change' %}active{% endif %}" href="{% url 'users:password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name == 'users:logout' %}active{% endif %}" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name == 'users:signup' %}active{% endif %}" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
        {% endwith %} 
      </ul>
    </div>
  </nav>      
</header> 